auto: true
safe: true
server: true
markdown: kramdown
pygments: true
permalink: /:title.html

default_theme: ribbon
default_body_class: list

author:
    name: Vadim Makeev
    url:  http://pepelsbey.net/
    company:
        name: Opera Software
        url:  http://opera.com

fork_url: https://github.com/shower/shower
progress: true
